/* tslint:disable */
/* eslint-disable */
/**
 * SS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AuthorsAuthor
 */
export interface AuthorsAuthor {
    /**
     * 
     * @type {string}
     * @memberof AuthorsAuthor
     */
    'bio'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorsAuthor
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorsAuthor
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface AuthorsCreateAuthorDto
 */
export interface AuthorsCreateAuthorDto {
    /**
     * 
     * @type {string}
     * @memberof AuthorsCreateAuthorDto
     */
    'bio'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorsCreateAuthorDto
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface AuthorsUpdateAuthorDto
 */
export interface AuthorsUpdateAuthorDto {
    /**
     * 
     * @type {string}
     * @memberof AuthorsUpdateAuthorDto
     */
    'bio'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorsUpdateAuthorDto
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface UtilApiError
 */
export interface UtilApiError {
    /**
     * 
     * @type {string}
     * @memberof UtilApiError
     */
    'message'?: string;
}

/**
 * AuthorsApi - axios parameter creator
 * @export
 */
export const AuthorsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a list of all authors
         * @summary List all authors
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authorsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/authors/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete an existing author by ID
         * @summary Delete author
         * @param {string} id Author ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authorsIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('authorsIdDelete', 'id', id)
            const localVarPath = `/authors/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a single author by their ID
         * @summary Get author by ID
         * @param {string} id Author ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authorsIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('authorsIdGet', 'id', id)
            const localVarPath = `/authors/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an existing author by ID
         * @summary Update author
         * @param {string} id Author ID
         * @param {AuthorsUpdateAuthorDto} data Author data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authorsIdPut: async (id: string, data: AuthorsUpdateAuthorDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('authorsIdPut', 'id', id)
            // verify required parameter 'data' is not null or undefined
            assertParamExists('authorsIdPut', 'data', data)
            const localVarPath = `/authors/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new author
         * @summary Create author
         * @param {AuthorsCreateAuthorDto} data Author data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authorsPost: async (data: AuthorsCreateAuthorDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('authorsPost', 'data', data)
            const localVarPath = `/authors/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthorsApi - functional programming interface
 * @export
 */
export const AuthorsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthorsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get a list of all authors
         * @summary List all authors
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authorsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AuthorsAuthor>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authorsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorsApi.authorsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete an existing author by ID
         * @summary Delete author
         * @param {string} id Author ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authorsIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authorsIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorsApi.authorsIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a single author by their ID
         * @summary Get author by ID
         * @param {string} id Author ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authorsIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthorsAuthor>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authorsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorsApi.authorsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update an existing author by ID
         * @summary Update author
         * @param {string} id Author ID
         * @param {AuthorsUpdateAuthorDto} data Author data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authorsIdPut(id: string, data: AuthorsUpdateAuthorDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthorsAuthor>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authorsIdPut(id, data, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorsApi.authorsIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new author
         * @summary Create author
         * @param {AuthorsCreateAuthorDto} data Author data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authorsPost(data: AuthorsCreateAuthorDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthorsAuthor>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authorsPost(data, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthorsApi.authorsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthorsApi - factory interface
 * @export
 */
export const AuthorsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthorsApiFp(configuration)
    return {
        /**
         * Get a list of all authors
         * @summary List all authors
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authorsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<AuthorsAuthor>> {
            return localVarFp.authorsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Delete an existing author by ID
         * @summary Delete author
         * @param {string} id Author ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authorsIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authorsIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a single author by their ID
         * @summary Get author by ID
         * @param {string} id Author ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authorsIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<AuthorsAuthor> {
            return localVarFp.authorsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an existing author by ID
         * @summary Update author
         * @param {string} id Author ID
         * @param {AuthorsUpdateAuthorDto} data Author data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authorsIdPut(id: string, data: AuthorsUpdateAuthorDto, options?: RawAxiosRequestConfig): AxiosPromise<AuthorsAuthor> {
            return localVarFp.authorsIdPut(id, data, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new author
         * @summary Create author
         * @param {AuthorsCreateAuthorDto} data Author data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authorsPost(data: AuthorsCreateAuthorDto, options?: RawAxiosRequestConfig): AxiosPromise<AuthorsAuthor> {
            return localVarFp.authorsPost(data, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthorsApi - object-oriented interface
 * @export
 * @class AuthorsApi
 * @extends {BaseAPI}
 */
export class AuthorsApi extends BaseAPI {
    /**
     * Get a list of all authors
     * @summary List all authors
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorsApi
     */
    public authorsGet(options?: RawAxiosRequestConfig) {
        return AuthorsApiFp(this.configuration).authorsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete an existing author by ID
     * @summary Delete author
     * @param {string} id Author ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorsApi
     */
    public authorsIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return AuthorsApiFp(this.configuration).authorsIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a single author by their ID
     * @summary Get author by ID
     * @param {string} id Author ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorsApi
     */
    public authorsIdGet(id: string, options?: RawAxiosRequestConfig) {
        return AuthorsApiFp(this.configuration).authorsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update an existing author by ID
     * @summary Update author
     * @param {string} id Author ID
     * @param {AuthorsUpdateAuthorDto} data Author data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorsApi
     */
    public authorsIdPut(id: string, data: AuthorsUpdateAuthorDto, options?: RawAxiosRequestConfig) {
        return AuthorsApiFp(this.configuration).authorsIdPut(id, data, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new author
     * @summary Create author
     * @param {AuthorsCreateAuthorDto} data Author data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorsApi
     */
    public authorsPost(data: AuthorsCreateAuthorDto, options?: RawAxiosRequestConfig) {
        return AuthorsApiFp(this.configuration).authorsPost(data, options).then((request) => request(this.axios, this.basePath));
    }
}



